[package]
name = "appdev"
version = "0.1.0"
edition = "2024"

[dependencies]
libcommon = { git = "https://github.com/munch1182/p2.git", branch = "master", package = "libcommon" }
tokio = { version = "1.47", features = ["rt-multi-thread", "macros"] }
