[package]
name = "pluginr_aaa"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pluginr_interface = { path = "../pluginr_interface" }
serde = { version = "1.0", features = ["derive"] }
