[package]
name = "pluginf_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.8"
libcommon = { git = "https://github.com/munch1182/p2.git", branch = "master", package = "libcommon" }
pluginf_interface = { path = "../pluginf_interface" }
libc = "0.2"
