POST http://127.0.0.1:3000/graphql
Content-Type: application/json

{
  "query": "query { users { id name createdAt } }"
}

###

POST http://127.0.0.1:3000/graphql
Content-Type: application/json

{
  "query": "query { user(id:2) { name email} }"
}

###

POST http://127.0.0.1:3000/graphql
Content-Type: application/json

{
  "query": "mutation { crateUser(input: { name: \"test3\", email: \"test3@example.com\" }) }"
}

###

POST http://127.0.0.1:3000/graphql
Content-Type: application/json

{
  "query": "mutation { deleteUser(id:3) }"
}