[package]
name = "axum_graphql"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.0"
async-graphql-axum = "7.0"
async-stream = "0.3.6"
axum = "0.8"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.47", features = ["full"] }
