[package]
name = "pluginf_aaa"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
libcommon = { git = "https://github.com/munch1182/p2.git", branch = "master", package = "libcommon" }
pluginf_interface = { path = "../pluginf_interface" }
